name: Secrets Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  do-normal-task:
    name: Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Use Variable
        env:
          SECRET: ${{ secrets.SUPER_SECRET_VARIABLE }}
          run: echo $SECRET